# Use an existing image as the base image
FROM python3.7-slim-buster

# Set the working directory
WORKDIR app

# Copy the requirements file
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app files
COPY . .

# Set the environment variables
ENV PORT 80

# Specify the command to run when the container starts
CMD [gunicorn, --workers, 4, --bind, 0.0.0.080, wsgiserver]
